# following three lines provide META-DATA for current object
apiVersion: v1  # k8s API version
kind: Pod       # Type pf OBJECT this file manages/deploys
metadata:
  name: pod1    # Unique name for this object
  labels:       # Optional labels (User defined key/value pairs)
    name: web1
  
# The actual object (POD) definition 
spec:
  containers:   # list of containers (now SINGLE)
  # start of first (and only container)
  - name: web1  # name for container
    image: mahendrshinde/myweb:latest  # container image from my 
    # Optional resource contraints
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    # application port (nginx uses 80)
    ports:
      - containerPort: 80
