# following lines provide META-DATA for current object
apiVersion: v1  # k8s API version
kind: Pod       # Type pf OBJECT this file manages/deploys
metadata:
  name: pod3    # Unique name for this object
  labels:       # Optional labels (User defined key/value pairs)
    name: web3
  
# The actual object (POD) definition 
spec:
  containers:   # list of containers 
  # start of first container
  - name: web3  # name for container
    image: nginx:1.7.9  # container image 
    # Optional resource contraints
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # application port (nginx uses 80)
    ports:
      - containerPort: 80
    # start of second container
  - name: db1
    image: mysql:5.7 
    # Setting environment variables for MySQL Database
    env:
      # Every variable need "name" and "value"
      - name: MYSQL_USER
        value: mahendra
      - name: MYSQL_PASSWORD
        value: pass@1234
      - name: MYSQL_ROOT_PASSWORD
        value: Pass123456      
    resources:
      limits:
        memory: "256Mi"
        cpu: "100m"
    ports:
      - containerPort: 3306
  # start of third container
  - name: test
    image: busybox
    imagePullPolicy: Never
    command: ['sh','-c','echo Hello World && sleep 3600']
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"